<div ID="imprimirSector">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>	
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />	
        <title>Confirmaci&oacute;n</title>	
        <style type="text/css"> 
        <!--
        .Base {font-family: Tahoma; font-size: 11px; color: #000000; }	
        .BorderColor {border-color:#E6E6E6; border-collapse:collapse}	
        .Cot {font-family: Tahoma; font-size: 17px; color: #000000}	
        .TopBot {font-family: Tahoma; font-size: 11px; color: #000000}	
        .PieTxt {font-family: Tahoma; font-size: 11px; color: #666666; text-align:justify}	
        .it {font-family: Tahoma; font-size: 9px; color: #666666; text-align:justify}	
        .NotaRojo {font-family: Tahoma; font-size: 15px; color: #990000; word-spacing:2px; line-height:15px}
        -->
        </style>
    </head>
    <body leftmargin="2" topmargin="2" marginwidth="2" marginheight="2" class="Base" >	 	
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">	  
            <tr>
                <td align="left">
                    <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>logo.jpg" alt="ALLWAYS" height="130" vspace="5" border="0" />
                </td>
                <td width="50%" align="right" class="TopBot">
                    <strong class="TopBot">
                        ALL WAYS Travel - TOUR OPERADOR MAYORISTA</strong><br />
                        Fidel Ote&iacute;za 1916, Of. 302, Providencia<br />
                        Teléfonos : (56) 2897 8000<br /><br />	      
                        <a href="http://www.allwaystravel.cl" target="_blank"> http://www.allwaystravel.cl <br /></a>
                        <br />
                        Santiago, <?php echo date("d F Y"); ?>
                </td>


            </tr>	
        </table>	
        <br />

        <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
            <tr>
                <td height="60" colspan="3" align="center"><span class="Cot">Confirmaci&oacute;n de Reserva Online</span></td>
            </tr>	  
            <tr>
                <td><strong>N&deg; File</strong></td>
                <td>:</td>
                <td><?php echo $this->numFile; ?></td>
                </tr>


            <tr>
                <td width="18%"><strong>Agencia</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->CC_agencia; ?></td>
            </tr>

            <tr>
                <td width="18%"><strong>Atenci&oacute;n</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->CC_vage; ?></td>
            </tr>

            <tr>
                <td width="18%"><strong>Paxs</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->CC_nomPax; ?></td>
            </tr>

            <tr>
                <td width="18%"><strong>N&deg; Pax</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->CC_nPax; ?></td>
            </tr>

            <tr>
                <td><strong>Fecha Viaje </strong></td>
                <td>:</td>
                <td><?php echo $this->CC_fviaje; ?></td>	  
            </tr>

            <tr>
                <td><strong>Programa </strong></td>
                <td>:</td>
                <td><?php echo $this->CC_nombreProg; ?></td>	  
            </tr>

        </table>
        <br />


        <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
            <tr>
                <td colspan="3">Estimada(o) <?php echo $this->CC_vage; ?></td>
            </tr>

            <tr>
                <td colspan="3">De acuerdo a lo solicitado, confirmo los siguientes servicios: </td>
            </tr>
            <tr>
                <td colspan="3"><hr noshade="noshade" /></td>
            </tr>
        </table>
        &nbsp; &nbsp; &nbsp; Incluye:<br />
        
        <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
            <tr>
                <td bordercolor="#FFFFFF">
                    <table width="100%" border="0" cellpadding="2" cellspacing="2">	
                        <?php 
                        if($this->CC_objsDetFile!=false)
                        {
                            
                            //while($row_detfile = mssql_fetch_array($res_detfile))
                            for($i=0; $i<$this->CC_objsDetFileCNT; $i++)
                            {
                                $s_1= $this->CC_objsDetFile[$i]->getPaxS();
                                $s_2= $this->CC_objsDetFile[$i]->getPaxD();
                                $s_3= $this->CC_objsDetFile[$i]->getPaxT();
                                $s_4= $this->CC_objsDetFile[$i]->getPaxQ();
                                $s_5= $this->CC_objsDetFile[$i]->getPaxA();
                                $s_6= $this->CC_objsDetFile[$i]->getPaxI();
                                $s_7= $this->CC_objsDetFile[$i]->getPaxC1();
                                $s_8= $this->CC_objsDetFile[$i]->getPaxCA();
                                $s_9= $this->CC_objsDetFile[$i]->getPaxC2();
                                
                                
                                /*if($row_detfile["pax_s"] <> "" && $row_detfile["pax_s"] <> "0")
                                        $s_1 = intval($row_detfile["pax_s"]);
                                if($row_detfile["pax_d"] <> "" && $row_detfile["pax_d"] <> "0")
                                        $s_2 = intval($row_detfile["pax_d"]);
                                if($row_detfile["pax_t"] <> "" && $row_detfile["pax_t"] <> "0")
                                        $s_3 = intval($row_detfile["pax_t"]);
                                if($row_detfile["pax_q"] <> "" && $row_detfile["pax_q"] <> "0")
                                        $s_4 = intval($row_detfile["pax_q"]);
                                if($row_detfile["pax_a"] <> "" && $row_detfile["pax_a"] <> "0")
                                        $s_5 = intval($row_detfile["pax_a"]);
                                if($row_detfile["pax_i"] <> "" && $row_detfile["pax_i"] <> "0")
                                        $s_6 = intval($row_detfile["pax_i"]);
                                if($row_detfile["pax_c"] <> "" && $row_detfile["pax_c"] <> "0")
                                        $s_7 = intval($row_detfile["pax_c"]);
                                if($row_detfile["pax_ca"] <> "" && $row_detfile["pax_ca"] <> "0")
                                        $s_8 = intval($row_detfile["pax_ca"]);
                                if($row_detfile["pax_c2"] <> "" && $row_detfile["pax_c2"] <> "0")
                                        $s_9 = intval($row_detfile["pax_c2"]);*/

                                $suma_total = $s_1 + $s_2 + $s_3 + $s_4 + $s_5 + $s_6 + $s_7 + $s_8 + $s_9 ;

                                echo '<tr>
                                        <td width="80%" class="Base">
                                            <strong>&middot;</strong>&nbsp; '.$suma_total.' Pax '.$this->CC_objsDetFile[$i]->getNombre().'<strong></strong>
                                        </td>
                                        <td width="10%" class="Base">';


                                        if($this->CC_objsDetFile[$i]->getIn() == "01/01/1900")
                                        {
                                            echo '';
                                        }
                                        else
                                        {
                                            echo $this->CC_objsDetFile[$i]->getIn(); 
                                        }


                                    echo '</td>
                                        <td width="10%" class="Base">';


                                    if($this->CC_objsDetFile[$i]->getOut() == "01/01/1900")
                                    {
                                        echo '';
                                    }
                                    else
                                    {
                                        echo $this->CC_objsDetFile[$i]->getOut();
                                    }


                                    echo '</td></tr>';
                            }
                        }
                        else
                        {
                            echo '<tr><td>Error al cargar el incluye</td></tr>';
                        }
                        ?>
                    </table>
                </td>
            </tr>	
        </table>
        <br />


        <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
            <tr>
                <td bordercolor="#FFFFFF">
                    <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
                        <tr>
                            <td width="25%">&nbsp;</td>
                            <td>&nbsp;</td>
                            <td width="75%">
                                <table width="100%" border="0" cellspacing="2" cellpadding="2">
                                    <tr>
                                        <td class="Base">Valores expresados en 
                                            <?php
                                            if ($this->CC_moneda == 'D')
                                            {
                                                echo 'D&oacute;lares Americanos (USD)'; 
                                            }
                                            elseif($this->CC_moneda == 'P')
                                            {
                                                echo 'Pesos Chilenos ($)';
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>


                        <tr>
                            <td width="25%"><strong>&nbsp;Valor Total</strong></td>
                            <td>:</td>
                            <td width="75%">
                            <?php
                                if($this->CC_totventa)
                                {
                                    echo Functions::formatoValor($this->CC_moneda, $this->CC_totventa) . ' + ' .Functions::formatoValor($this->CC_moneda, $this->CC_ajuste).' (Impuestos)'; 
                                }
                                ?>
                            </td>
                        </tr>

                        <tr>
                            <td width="25%"><strong>&nbsp;Tiempo limite de pago</strong></td>
                            <td width="2%">:</td>
                            <td width="75%" class="Base"> 48 horas</td>
                        </tr>

                        <?php			
                        if ($this->CC_moneda == "D")
                        {		
                        echo '<tr><td width="25%"><strong>&nbsp;Tipo de cambio al d&iacute;a de hoy </strong></td>
                                        <td width="2%">:</td>
                                        <td width="75%">
                                                '.$this->CC_cambio.' (Consultar al momento del pago)
                                        </td>
                                </tr>';
                        }
                        ?>		



                        <tr>
                            <td width="25%"><strong>&nbsp;Comisi&oacute;n:</strong></td>
                            <td width="2%">:</td>
                            <td width="75%"><?php echo $this->CC_comag; ?>%
                                <?php
                                if($this->CC_tcomi == 1)
                                {
                                    echo ' + I.V.A.';
                                }
                                elseif($this->CC_tcomi == 2)
                                {
                                    echo ' I.V.A. Incluido';
                                }
                                ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br />

        <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
            <tr>
                <td bordercolor="#FFFFFF">
                    <table width="100%" border="0" cellpadding="2" cellspacing="2" class="Base">
                        <tr>
                            <th></th>
                            <th>Tipo</th>
                            <th>Nombre</th>
                            <th>Rut</th>
                            <th>Fecha nacimiento</th>
                            <th>Nombre Infant</th>
                            <th>Rut Infant</th>
                            <th>Fecha nacimiento Infant</th>
                        </tr>
                        <?php
                        $contador = 1; 
                        //while($row_detbloq = mssql_fetch_array($res_detbloq)) 
                        if($this->CC_objsDetBloq!=false)
                        {
                            for($i=0; $i<$this->CC_objsDetBloqCNT; $i++)
                            {
                                echo '<tr>
                                        <td>'.$contador.'</td>
                                        <td>';
                                
                                if($this->CC_objsDetBloq[$i]->getTipoPax() == "A")
                                {
                                    echo 'Adulto';
                                }
                                elseif($this->CC_objsDetBloq[$i]->getTipoPax() == "C")
                                {
                                    echo 'Child';
                                }

                                echo '</td>
                                        <td>'.str_replace('/', ' ', $this->CC_objsDetBloq[$i]->getNomPax()).'</td>
                                        <td>'.$this->CC_objsDetBloq[$i]->getRut().'</td>
                                        <td>';
                                        if($this->CC_objsDetBloq[$i]->getFChild() == "01/01/1900")
                                        {
                                            echo '';
                                        }
                                        else
                                        {
                                            echo $this->CC_objsDetBloq[$i]->getFChild();
                                        }

                                $html.='</td>
                                        <td>'.$this->CC_objsDetBloq[$i]->getNInfant().'</td>
                                        <td>'.$this->CC_objsDetBloq[$i]->getRutInf().'</td>
                                        <td>';

                                        if($this->CC_objsDetBloq[$i]->getFInfant() == "01/01/1900")
                                        {
                                            echo ''; 
                                        }
                                        else
                                        {
                                            echo $this->CC_objsDetBloq[$i]->getFInfant();
                                        }
                                        echo '</td>
                                </tr>';

                                $contador = $contador + 1;
                            }
                        }
                        ?>
                        <tr>
                            <td colspan="8" style="font-weight:bold;">&nbsp;</td>
                        </tr>
                        <tr>
                            <td colspan="8" style="font-weight:bold;">Itinerario de vuelo:</td>
                        </tr>
                        <tr>
                            <td colspan="8"><?php echo $this->CC_notas; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>	
        </table>
        <br />

        <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">

            <tr class="TopBot">
                    <td colspan="3">DEPARTAMENTO RESERVA</td>
                    </tr>
            </table>








            <style>
                <!--
                    @media print{
                        .oculto{display:none}
                    }
                -->
            </style>
            <center>
                <div style="width:90%; text-align:right;" >
                    <img class="oculto" src="<?php echo $_layoutParamsCB['ruta_img']; ?>print.png" onClick="javascript:imprSelec('imprimirSector')" width="32" style="cursor:pointer;" /> &nbsp;<br />&nbsp;
                </div>
            </center>
            <br /><br />
        </body>
        
</html>
</div>
<script language="Javascript">
    function imprSelec(nombre)
    {
        var ficha = document.getElementById(nombre);
        var ventimp = window.open(' ', 'popimpr');
        ventimp.document.write( ficha.innerHTML );
        ventimp.document.close();
        ventimp.print( );
        ventimp.close();
    }
</script>