
<tr>
    <td width="20px">
        <input type="radio" name="P_rdbOpcion_1" value="892">
    </td>
    <td>
        <a id="div_opc_hotelProg_1" style="cursor:pointer" title="">CABANAS RAPA NUI ORITO</a>
    </td>
    <td style="color:#F00;" width="105px">$ 930.900</td>
    <td width="24px">
        <a data-toggle="modal" href="#myModal" onclick="abrePopup('divPopupPRG', 'http://jonathan-pc/allways/system/notas', 'tituloFormPRG', 'Nota de Programa', '892');">
            <img src="http://jonathan-pc/allways/views/layout/default/img/nota.png" width="24px" alt="Notas" title="Notas">
        </a></td>
</tr>
<tr>
    <td width="20px">
        <input type="radio" name="P_rdbOpcion_1" value="893">
    </td><td><a id="div_opc_hotelProg_2" style="cursor:pointer" title="">MANUTARA</a></td><td style="color:#F00;" width="105px">$ 1.200.900</td>
    <td width="24px"><a data-toggle="modal" href="#myModal" onclick="abrePopup('divPopupPRG', 'http://jonathan-pc/allways/system/notas', 'tituloFormPRG', 'Nota de Programa', '893');">
            <img src="http://jonathan-pc/allways/views/layout/default/img/nota.png" width="24px" alt="Notas" title="Notas">
        </a></td>
</tr>
<tr>
    <td width="20px">
        <input type="radio" name="P_rdbOpcion_1" value="895">
    </td><td><a id="div_opc_hotelProg_3" style="cursor:pointer" title="">OCEANIA RAPA NUI</a></td><td style="color:#F00;" width="105px">$ 1.182.900</td>
    <td width="24px"><a data-toggle="modal" href="#myModal" onclick="abrePopup('divPopupPRG', 'http://jonathan-pc/allways/system/notas', 'tituloFormPRG', 'Nota de Programa', '895');">
            <img src="http://jonathan-pc/allways/views/layout/default/img/nota.png" width="24px" alt="Notas" title="Notas">
        </a></td>
</tr>
