<table align="center">
    <tr>
        <td align="center">
            <div class="col-md-12">
                <ul class="gallery list-unstyled">
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <img src="<?php echo $_layoutParamsCB['ruta_fotos_hotel'] . $this->objHotel[0]->getImgEnc(); ?>" width="300" height="250">
                    </li>

                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <img src="<?php echo $_layoutParamsCB['ruta_fotos_hotel'] . $this->objHotel[0]->getImgCont(); ?>" width="300" height="250">
                    </li>

                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <img src="<?php echo $_layoutParamsCB['ruta_fotos_hotel'] . $this->objHotel[0]->getImgCont2(); ?>" width="300" height="250">
                    </li>

                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <img src="<?php echo $_layoutParamsCB['ruta_fotos_hotel'] . $this->objHotel[0]->getImgCont3(); ?>" width="300" height="250">
                    </li>

                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <img src="<?php echo $_layoutParamsCB['ruta_fotos_hotel'] . $this->objHotel[0]->getImgCont4(); ?>" width="300" height="250">
                    </li>
               </ul>
            </div>
        </td>
    </tr>
</table>