<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <h1>Bienvenido!</h1>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">


                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Estas son algunas de nuestras &uacute;ltimas ofertas.</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-md-12">
                                        <center>
                                            <iframe src="http://allwaystravel.cl/slide/index_slide.html" width="733" height="321" frameborder="0"></iframe>
                                        </center>
                                    </div>

                                </div>
                            </div>
                        </div>	





                    </div>
                </div>
            </div>
        </div>

    </div> <!--wrap -->
</div> <!-- page-content -->

