<script>
$('.blink').each(function() {
        var elem = $(this);
        setInterval(function() {
            
            elem.animate({opacity: 0}, 400);
            elem.animate({opacity: 1}, 400);
            
        }, 1000);
    });
</script>
<div class="panel panel-primary" id="DP_principal" style="display: block;">
    <div class="panel-heading">

        <?php echo $this->objProgramas[0]->getTitulo(); ?>

        <div class="options">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#home1" data-toggle="tab">Tarifas</a>
                </li>
                <li>
                    <a href="#profile1" data-toggle="tab">Condiciones</a>
                </li>
            </ul>
        </div>

    </div>
    
    
    <div class="panel-body">
        <div class="tab-content">
            <div class="tab-pane active" id="home1" >
                <div>

                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                        <tr>
                            <td colspan="2">
                                <P style="font-size:11px">
                                    <b style="color:#FF9900;">PAIS:</b> <?php echo $this->objProgramas[0]->getPais(); ?>, 
                                    <b style="color:#FF9900; margin-left: 10px;">CIUDAD:</b> <?php echo $this->objProgramas[0]->getCiudad(); ?> 
                                    <label style="margin-right: 30px;">&nbsp;</label>
                                    <?php if($this->objProgramas[0]->getAereo()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;" > Aereo <?php } ?>
                                    <?php if($this->objProgramas[0]->getHotel()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;"> Hotel <?php } ?>
                                    <?php if($this->objProgramas[0]->getTraslado()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;" > Traslado <?php } ?>
                                </P>
                            </td>
                        </tr>
                        <tr>
                            <td width="210" valign="top">
                                <img src="<?php echo $_layoutParamsCB['ruta_programas']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                            </td>
                            <td>
                                <?php echo $this->objProgramas[0]->getIncluye(); ?>
                            </td>
                        </tr>
                    </table>

                </div>

            </div>


            <div class="tab-pane" id="profile1">
                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                        <tr>
                            <td colspan="2">
                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                    <?php echo $this->objProgramas[0]->getNota(); ?>
                                </p>
                            </td>
                        </tr>
                        <!-- <tr>
                            <td>
                                <p>
                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                </p>
                            </td>
                            <td>
                                <p>

                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 

                                </p>
                            </td>
                        </tr> -->
                    </table>
            </div>
        </div>
    </div>
    
    
    
    
    
    
    
<?php
if($this->objOpcProgramas) {
    $cntDP = 1;
    foreach($this->objOpcProgramas as $objOpcProg) {
?>
    <br />
    <div class="panel-heading" style="margin-top: 20px;" >
        Opci&oacute;n  <?php echo $cntDP; ?> <div class="blink" style="float: right;"><button class="btn btn-warning btn-sm" > &iexcl; DISPONIBLE ! </button><?php //echo $objOpcProg->getEstado(); ?></div>
    </div> 
    <div class="panel-body">
        <div class="tab-content" style="display: block;" id="tab_content_1_<?php echo $cntDP; ?>">
            
            
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" style="font-size:12px; width: 100%; margin-top: 20px;" align='center'> <!-- class="table table-striped table-bordered" -->
                <thead>
                    <tr style="background-color:#34495e; color: #FFFFFF" role="row">
                        <th role="columnheader" style="padding-left: 2px;">Hotel</th>
                        <th role="columnheader" style="padding-left: 2px;">Direcci&oacute;n</th>
                        <th role="columnheader" style="padding-left: 2px;">Categoria</th>
                        <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                    </tr>
                </thead>
                
                <?php 
                $DP_hoteles= $objOpcProg->getNombreHotel();
                $DP_dirHot= $objOpcProg->getDir();
                $DP_catHot= $objOpcProg->getCat();
                $DP_thHot= $objOpcProg->getTipoHab();
                $DP_cntHoteles = count($objOpcProg->getNombreHotel());
                
                for($i = 0; $i < $DP_cntHoteles; $i++) {
                ?>
                    <tr>
                        <td style="color: #DF5F00; padding: 2px; vertical-align: middle;"><?php echo $DP_hoteles[$i]; ?></td>
                        <td style="width: 300px;"><?php echo $DP_dirHot[$i]; ?></td>
                        <td style="width: 80px;"><?php echo $DP_catHot[$i]; ?></td>
                        <td style="padding: 2px; vertical-align: middle; width: 100px;"><?php echo $DP_thHot[$i]; ?></td>
                    </tr>
                    <tr>
                        <td style="color: #DF5F00; padding: 2px; vertical-align: middle;"><?php echo $DP_hoteles[$i]; ?></td>
                        <td style="width: 300px;"><?php echo $DP_dirHot[$i]; ?></td>
                        <td style="width: 80px;"><?php echo $DP_catHot[$i]; ?></td>
                        <td style="padding: 2px; vertical-align: middle; width: 100px;"><?php echo $DP_thHot[$i]; ?></td>
                    </tr>
                    <?php
                }?>
            </table>
            
            
            
            <!-- RESERVAR -->
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" align="center">
                <tr>
                    <td style="font-size: 12px; text-align: center"> SINGLE </td>
                    <td style="font-size: 12px; text-align: center"> DOBLE </td>
                    <td style="font-size: 12px; text-align: center"> TRIPLE </td>
                    <td style="font-size: 12px; text-align: center"> </td>
                </tr>

                <tr>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenSGL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenDBL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenTPL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <a id="btnDP_reservar_<?php echo $cntDP; ?>" class="btn btn-success btn-sm" style="width: 88px;" onclick="pasajerosProg('<?php echo $cntDP; ?>', 'tab_content_1_<?php echo $cntDP; ?>', 'tab_content_2_<?php echo $cntDP; ?>', '<?php echo BASE_URL; ?>programas/pasajeros');"> RESERVAR </a>
                    </td>
                </tr>
            </table>
            
            <!-- END: RESERVAR -->
            
        </div>
        
        <div class="tab-content" style="display: none;" id="tab_content_2_<?php echo $cntDP; ?>"></div>
        
    </div>
    
<?php $cntDP++; } } ?>   
    
    
</div>